from __future__ import annotations

import math
import shutil
from pathlib import Path

from app.models.schema import VideoAspect
from app.services import material

from .models import MorrowglassProject


class ImageGenerationUnavailable(RuntimeError):
    pass


def mpt_openai_image_ready() -> bool:
    """Return whether MoneyPrinterTurbo's OpenAI-compatible image source is configured."""
    return bool(material.is_openai_image_enabled())


def generate_missing_scene_images(
    project: MorrowglassProject,
    project_dir: str | Path,
    *,
    overwrite: bool = False,
) -> list[str]:
    """Generate one scene-specific image for every scene that has no asset.

    Uses MoneyPrinterTurbo's existing OpenAI-compatible /images/generations backend.
    This can point at a local gateway or a cloud provider configured in config.toml.
    Returns scene ids that could not be generated.
    """
    if not mpt_openai_image_ready():
        raise ImageGenerationUnavailable(
            "OpenAI-compatible image generation is not configured. "
            "Set openai_image_base_url and openai_image_model in config.toml, "
            "or keep HYBRID mode and create the prompt-pack images manually."
        )

    project_dir = Path(project_dir)
    images_dir = project_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    failures: list[str] = []
    for scene in project.scenes:
        existing = Path(scene.asset_path) if scene.asset_path else None
        if existing and existing.is_file() and not overwrite:
            continue

        target = images_dir / f"{scene.scene_id}.png"
        if target.is_file() and not overwrite:
            scene.asset_path = str(target.resolve())
            continue

        duration = scene.duration if scene.duration is not None else 5.0
        minimum_duration = max(1, int(math.ceil(duration)))
        results = material.generate_images_openai(
            search_term=scene.image_prompt,
            minimum_duration=minimum_duration,
            video_aspect=VideoAspect.landscape,
            save_dir=str(images_dir),
        )
        if not results:
            failures.append(scene.scene_id)
            scene.qc_notes.append("image generation returned no usable image")
            continue

        source = Path(results[0].url)
        if not source.is_file():
            failures.append(scene.scene_id)
            scene.qc_notes.append("image provider returned a missing local file")
            continue

        if target.exists():
            target.unlink()
        if source.resolve() != target.resolve():
            shutil.move(str(source), str(target))
        scene.asset_path = str(target.resolve())
        scene.qc_notes.append("generated by mpt_openai image provider")

    project.metadata["image_provider"] = "mpt_openai"
    project.metadata["image_generation_failures"] = failures
    project.save(project_dir / "project.json")
    return failures
